### ISSUE TITLE
unique strings gets thrown off by formatted strings

### ISSUE THREAD

**Issue by slyrus** [a1b10/cl-xlsx#6]
If an xlsx file has a shared string such as:

```
  <si>
    <r>
      <rPr>
        <sz val="10"/>
        <rFont val="Arial"/>
        <family val="2"/>
      </rPr>
      <t xml:space="preserve">Foo</t>
    </r>
    <r>
      <rPr>
        <sz val="10"/>
        <rFont val="Calibri"/>
        <family val="2"/>
      </rPr>
      <t xml:space="preserve">Bar</t>
    </r>
  </si>
```
this gets read as two separate strings and throws off the count of shared strings, meaning that references to strings after this are now incorrect. There's probably an easy klacks-based fix (or at least hacky workaround) but my klacks-foo is rusty. I have an xpath based version if you would consider using that.

**Comment by gwangjinkim** [comment]
Thank you! Sure - would be interested into that. It is a very provisoric package - to just handle simplest tables without big formatting. (kind of to use excel instead of csv while heaving the table contents more human readable). There will be a lot to improve. Therefore, any suggestions welcome. And when I have more time I will look at this in more detail. But at the moment - these weeks - I am in holidays.
